# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PAArchiveExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PAArchiveExample

  target 'PAArchiveExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PAArchiveExampleUITests' do
    # Pods for testing
  end

end
